// console.log(__filename)
// console.log(__dirname)
const path=require('path')
// console.log(path.basename(__filename))
// console.log(path.basename(__dirname))
// console.log(path.extname(__filename))
// console.log(path.extname(__dirname))
// console.log(path.isAbsolute(__filename))
// console.log(path.isAbsolute('C:/Users/venki/Documents/Node_2pm/Modules/built_in/Path/path.js'))
// console.log(path.isAbsolute('./path.js'))

// console.log(path.parse(__filename))
// console.log(path.format(path.parse(__filename)))

// console.log(path.join('folder1','folder2','node.js'))
// console.log(path.join('/folder1','folder2','node.js'))
// console.log(path.join('/folder1','//folder2','node.js'))
// console.log(path.join('folder1','folder2','../node.js'))

// console.log(path.resolve('folder1','folder2','node.js'))
// console.log(path.resolve('/folder1','folder2','node.js'))
// console.log(path.resolve('/folder1','//folder2','node.js'))
// console.log(path.resolve('/folder1','//folder2','../node.js'))